version: "2"

services:
  kusama-tools: &tools_base
    restart: always
    image: scan/codec_grpc
    build: .
    environment:
      NETWORK_NODE: 'kusama'
    networks:
      - app_net
  edgeware-tools:
    <<: *tools_base
    environment:
      NETWORK_NODE: 'edgeware'
  canary-tools:
    <<: *tools_base
    environment:
      NETWORK_NODE: 'canary'
  cert-tools:
    <<: *tools_base
    environment:
      NETWORK_NODE: 'cert'
networks:
  app_net:
    external: true
